_target_: src.models.ddpm_module.DDPMLitModule
diffusion_steps: 1000
beta_schedule: "cosine"
model_mean_type: "epsilon"
model_var_type: "learned_range"
loss_type: "rescaled_mse"
schedule_sampler: "uniform"
lr: 0.0001
weight_decay: 0.0
ema_start: 1000
ema_update: 10
ema_decay: 0.995
sample_every: 2000
num_sample_imgs: 9

net:
  _target_: src.models.components.unet.UNetModel
  image_size: 32
  in_channels: 3
  model_channels: 128
  out_channels: 6  # (3 if not learn_sigma else 6)
  num_res_blocks: 3
  attention_resolutions: [2, 4, 8]  # image_size // int(res) = attention resolution
  dropout: 0.1
  channel_mult: [1, 2, 3, 4]
